'use strict';
module.exports = [
  'Canadian geese',
  'Shrimp',
  'Thorny oyster',
  'Porpoise',
  'Indian ringnecked parakeet',
  'Horseshoe bat',
  'Tamandua mexicana (Northern anteater)',
  'Anteater',
  'Crab-eating opossum',
  'Siren',
  'Siren',
  'Cat & kitten',
  'Ivory-billed woodpecker',
  'White spoonbill',
  'Panther',
  'Horny toad',
  'Moose',
  'Apallousa Horse',
  'Apallousa Horse',
  'Boston terrier',
  'Racoons',
  'Thorny woodcock',
  'Coyote',
  'Tadpoles',
  'Antelope',
  'Coelacanth',
  'Mastiff',
  'Cobra',
  'Kangaroo rat',
  'Kangaroo rat',
  'Peacock butterfly',
  'Carolina parakeets',
  'Cow',
  'Black-headed gull',
  'Garter snake',
  'Mole',
  'African crowned crane',
  'Chipmunk',
  'Coati',
  'Salmon',
  'Mouse',
  'Kiwi',
  'Black jaguar',
  'Domestic ass',
  'Blowfish',
  'Staghound',
  'Eels',
  'Minnows',
  'Camel',
  'Kestrel',
  'Frilled lizard',
  'Rabbit & frog',
  'Salmon',
  'Sheep',
  'Springbok',
  'Night monkey',
  'Gyr falcon',
  'Porcelain crab',
  'Reindeer',
  'Snake',
  'C. elegans',
  'Frilled coquette hummingbird',
  'Opossum',
  'Grasshopper',
  'Raven',
  'Wood duck',
  'Flamingo',
  'Auk bird',
  'Arab baboon',
  'Wallaby & joey',
  'Flat headed cats',
  'Bobacs',
  'Red deer',
  'Armadillo',
  'Armadillo',
  'Octopus',
  'Common mackerel',
  'Gannet',
  'Aye-aye',
  'Chimpanzee',
  'Chamois',
  'Cuttlefish',
  'Flying dragon',
  'Mouse',
  'Gnu',
  'Lion',
  'North African wild ass',
  'Koala',
  'Koala',
  'Ground squirrel',
  'Ground squirrel',
  'Polar bear',
  'Criss-cross fish & butterfly fish',
  'Trout & char',
  'Zebu',
  'Rigatella snail',
  'Mollusk',
  'Percheron',
  'Osprey',
  'Lions',
  'John Dory',
  'Red firefish',
  'Ermines',
  'Javan tiger',
  'Domestic fowl',
  'Lagotis',
  'Taguan',
  'Sand dollar',
  'Javan tiger',
  'Bison',
  'White rabbit',
  'Poodles',
  'Octopus',
  'Passenger pigeon',
  'River otter',
  'Pig-footed bandicoot',
  'Serval',
  'Hummingbird moths',
  'European red squirrel',
  'Tiger',
  'Fennec',
  'European bear',
  'Spider monkey',
  'Marine invertebrate',
  'European ibex',
  'Howler monkey',
  'Hippopotamus',
  'Rhino',
  'Rhino',
  'Grey wolf',
  'Barbary ape',
  'Grey wolf',
  'Springbok',
  'Yellow baboon',
  'Bank vole',
  'Barred owl',
  'Mink',
  'Goldfish',
  'Bloohounds',
  'Irish setter',
  'Gnu',
  'Tigress & cubs',
  'Zebra butterfly',
  'Gecko',
  'Llama',
  'Alpaca',
  'Wood rat',
  'Geometric tent tortoise',
  'Bass',
  'Hawksbill turtle',
  'Owl',
  'Tarsier',
  'Kitten',
  'Alaskan malamute',
  'Alaskan malamute',
  'Seal',
  'Snake-necked turtle',
  'Galago lemur',
  'Chick & egg',
  'Marabou stork',
  'Victoria crowned pigeons',
  'Rockhopper penguin',
  'Striped hyena',
  'Foxhound',
  'Foxhound',
  'German shepard',
  'German shepard',
  'Welsh terriers',
  'Belgian shepherd',
  'Kingfisher',
  'African bushback',
  'Donkey',
  'Woodpecker',
  'Bush baby',
  'Porcupines',
  'Potto',
  'Barbirusa',
  'Orangutan',
  'Seahorse',
  'Wolf',
  'Pyrops candelaria (lantern flies)',
  'Bullfrog',
  'Emu',
  'Owls',
  'Egyptian goose',
  'Green anole',
  'Kingfisher',
  'European tree frogs',
  'Steer',
  'Basilisk',
  'Land crab',
  'Cormorant',
  'Corsac',
  'Palm civet',
  'Yellowjacket',
  'Centipede',
  'Ladybug',
  'Tsetse fly',
  'Rosalie beetle',
  'Dragon fly & damsel fly',
  'Cicadas',
  'Silkworm moths',
  'Honey bee',
  'Red wood ants (female & male)',
  'Centipede',
  'Moth',
  'Stag beetle',
  'Ants',
  'Ants',
  'Female garden spiders',
  'Dung beetle',
  'Splendar beetle',
  'Hornets',
  'Scarab beetle',
  'Moving leaf insect',
  'Moving leaf insect',
  'Scorpion',
  'Bumble bee',
  'Herring gull',
  'Buntings',
  'Pigeon',
  'Flying squirrel',
  'Aoudad',
  'Blesbok',
  'West african green monkeys',
  'Camel',
  'Bighorn sheep',
  'Greater honeyguide',
  'Thread-winged lacewing ',
  'Sea otter',
  'Proboscis monkey',
  'Monkey',
  'Llama & camel',
  'Badger',
  'Emu (jeuvenile)',
  'Galapagos land iguana',
  'Cuckoo',
  'Cat & mouse',
  'Dove',
  'Kangaroo',
  'Mammoth',
  'Cow',
  'Chipmunk',
  'Thoroughbred horse',
  'Secretary bird',
  'Snipefish',
  'Crested pigeon',
  'Hermit crab',
  'Boatbill heron',
  'Sable antelope',
  'Stingray',
  'African crowned crane',
  'Arctic tern',
  'Ticks',
  'Spotted eagle',
  'Bellbird',
  'Percheron',
  'Smoothhound shark',
  'Darter',
  'Camel',
  'Cuckoo',
  'Rock python',
  'Great plover',
  'Cheetah',
  'Catfish',
  'Flying fish',
  'Flying dragon',
  'Sea sponge',
  'Jelly fish',
  'Pig deer',
  'Swan',
  'Toucan',
  'Silk worm',
  'Elephant shrew',
  'Spring Haas',
  'Rock python',
  'Caiman',
  'Harvest mice',
  'Tawny owl',
  'Dolium shell',
  'Greyhound',
  'Owls',
  'Blood pheasant',
  'Asiatic wild ram',
  'Tegu',
  'German shepherd',
  'Crows',
  'Hornbill',
  'Pampas cat',
  'Crested porcupine',
  'Slender lorises',
  'Slender lorises',
  'Common European bat',
  'Flying fox bat',
  'Flying fox bat',
  'Jacana',
  'Africa openbill',
  'Boa constricter',
  'Spotted salamander',
  'Chameleon',
  'Salamander',
  'Squid',
  'Snail',
  'Eastern chipmunks',
  'Sooty phalanger (brush-tailed possums) ',
  'Arcus pheasant',
  'Swordfish',
  'Caribou',
  'Monkey',
  'Land crab',
  'Great black cockatoo',
  'Toad & insect',
  'Snow leopard',
  'Tree Swift',
  'Wall creepers',
  'Kitten',
  'Gavial',
  'Tarsier',
  'Flies',
  'Turtle',
  'Oyster catcher',
  'North African ground hornbill',
  'Pika & hyrax',
  'Catfish',
  'Pinscher dog',
  'Tarsier',
  'Puffins',
  'Rock thrush',
  'Platypus',
  'Koala',
  'Sword billed humming bird',
  'Lioness',
  'Whale shark',
  'Spiny lobster',
  'Emu',
  'Wallaby & joey',
  'Sand star',
  'Wallaby & joey',
  'Entellus or hanuman monkey',
  'Man-o\'-war',
  'Crested eagle',
  'Stickleback fish',
  'European common toad',
  'Fat frog',
  'Horse shoe crab',
  'Caracara bird',
  'Surinam toad',
  'Climbing frog',
  'Parakeet',
  'White-tailed eagle',
  'Bluejay',
  'Beisa oryx',
  'Peacock',
  'Peafowl',
  'Tarpan',
  'Reeves\'s pheasant',
  'Bee eaters',
  'Pennant-winged night jar',
  'Jabiru',
  'Red mullet fish'
];
